[project]
name = "football_manager"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Alessandro Ferrante",email = "nerajarolle@gmail.com"},
]
dependencies = [
    "fastapi>=0.115.0",
    "nicegui>=3.16.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "uvicorn>=0.34.0",
]
requires-python = "==3.14.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts.dev]
cmd = "python app.py"

[tool.pdm.scripts.prod]
cmd = "python main.py"
