[pytest]
asyncio_mode = auto
main_file = app.py
addopts = -p nicegui.testing.user_plugin -p no:anyio
filterwarnings =
	ignore:Module already imported so cannot be rewritten; anyio:pytest.PytestAssertRewriteWarning
